apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-react-routes
spec:
  parentRefs:                 # Which Gateway and listener to attach to
    - name: gateway           # Gateway name
      namespace: gw-api-nginx
      sectionName: http       # Listener name from Gateway spec
  hostnames:
    - "af006cd626f3e4a95928241520bebdf7-712790669.us-east-1.elb.amazonaws.com"
  rules:                      # Routing rules
    - matches:
        - path:
            type: PathPrefix  # Match any path starting with /iphone
            value: /
      backendRefs:
        - name: bankapp-service    # Service to send traffic to
          port: 80
